from __future__ import annotations

from collections.abc import Mapping
from types import MappingProxyType

from garboid_pocketrocks.bots.base import BotSpec
from garboid_pocketrocks.bots.fixed_bid import (
    FIXED_BID_BOT_SPEC,
    FIXED_BID_DIVERSE_V1_BOT_SPEC,
    FIXED_BID_TUNED_NORMAL_V1_BOT_SPEC,
    FIXED_BID_TUNED_V1_BOT_SPEC,
)
from garboid_pocketrocks.bots.fixed_objective_overlay import (
    FIXED_OBJECTIVE_OVERLAY_V1_BOT_SPEC,
    FIXED_OBJECTIVE_OVERLAY_V2_BOT_SPEC,
    FIXED_OBJECTIVE_OVERLAY_V3_BOT_SPEC,
)
from garboid_pocketrocks.bots.heuristic import (
    AGGRESSIVE_HEURISTIC_BOT_SPEC,
    AGGRESSIVE_HEURISTIC_V1_BOT_SPEC,
    AGGRESSIVE_HEURISTIC_V2_BOT_SPEC,
    AGGRESSIVE_HEURISTIC_V3_BOT_SPEC,
    BALANCED_HEURISTIC_BOT_SPEC,
    BALANCED_HEURISTIC_V1_BOT_SPEC,
    BALANCED_HEURISTIC_V2_BOT_SPEC,
    BALANCED_HEURISTIC_V3_BOT_SPEC,
    PASSIVE_HEURISTIC_BOT_SPEC,
    PASSIVE_HEURISTIC_V1_BOT_SPEC,
    PASSIVE_HEURISTIC_V2_BOT_SPEC,
    PASSIVE_HEURISTIC_V3_BOT_SPEC,
)
from garboid_pocketrocks.bots.random_bot import RandomBot
from garboid_pocketrocks.bots.sdk_samples import SDK_GREEDY_VALUE_V1_BOT_SPEC
from garboid_pocketrocks.bots.surplus import (
    SURPLUS_BOT_SPEC,
    SURPLUS_V1_BOT_SPEC,
    SURPLUS_V2_BOT_SPEC,
    SURPLUS_V3_BOT_SPEC,
    SURPLUS_V4_BOT_SPEC,
    SURPLUS_V5_BOT_SPEC,
    SURPLUS_V6_BOT_SPEC,
    SURPLUS_V7_BOT_SPEC,
    SURPLUS_V8_BOT_SPEC,
    SURPLUS_V9_BOT_SPEC,
    SURPLUS_V10_BOT_SPEC,
    SURPLUS_V11_BOT_SPEC,
    SURPLUS_V12_BOT_SPEC,
)
from garboid_pocketrocks.neural.tournament_bot import (
    VECTOR_PPO_LARGE_V1_G350K_BOT_SPEC,
    VECTOR_PPO_SMALL_V1_G1500_BOT_SPEC,
)

BOT_SPECS = (
    BotSpec.from_bot_class(RandomBot),
    FIXED_BID_BOT_SPEC,
    FIXED_BID_TUNED_V1_BOT_SPEC,
    FIXED_BID_DIVERSE_V1_BOT_SPEC,
    FIXED_BID_TUNED_NORMAL_V1_BOT_SPEC,
    FIXED_OBJECTIVE_OVERLAY_V1_BOT_SPEC,
    FIXED_OBJECTIVE_OVERLAY_V2_BOT_SPEC,
    FIXED_OBJECTIVE_OVERLAY_V3_BOT_SPEC,
    AGGRESSIVE_HEURISTIC_BOT_SPEC,
    BALANCED_HEURISTIC_BOT_SPEC,
    PASSIVE_HEURISTIC_BOT_SPEC,
    AGGRESSIVE_HEURISTIC_V1_BOT_SPEC,
    BALANCED_HEURISTIC_V1_BOT_SPEC,
    PASSIVE_HEURISTIC_V1_BOT_SPEC,
    AGGRESSIVE_HEURISTIC_V2_BOT_SPEC,
    BALANCED_HEURISTIC_V2_BOT_SPEC,
    PASSIVE_HEURISTIC_V2_BOT_SPEC,
    AGGRESSIVE_HEURISTIC_V3_BOT_SPEC,
    BALANCED_HEURISTIC_V3_BOT_SPEC,
    PASSIVE_HEURISTIC_V3_BOT_SPEC,
    SDK_GREEDY_VALUE_V1_BOT_SPEC,
    SURPLUS_BOT_SPEC,
    SURPLUS_V1_BOT_SPEC,
    SURPLUS_V2_BOT_SPEC,
    SURPLUS_V3_BOT_SPEC,
    SURPLUS_V4_BOT_SPEC,
    SURPLUS_V5_BOT_SPEC,
    SURPLUS_V6_BOT_SPEC,
    SURPLUS_V7_BOT_SPEC,
    SURPLUS_V8_BOT_SPEC,
    SURPLUS_V9_BOT_SPEC,
    SURPLUS_V10_BOT_SPEC,
    SURPLUS_V11_BOT_SPEC,
    SURPLUS_V12_BOT_SPEC,
    VECTOR_PPO_SMALL_V1_G1500_BOT_SPEC,
    VECTOR_PPO_LARGE_V1_G350K_BOT_SPEC,
)

DEFAULT_TOURNAMENT_BOT_SPECS = (
    FIXED_OBJECTIVE_OVERLAY_V3_BOT_SPEC,
    FIXED_OBJECTIVE_OVERLAY_V2_BOT_SPEC,
    FIXED_OBJECTIVE_OVERLAY_V1_BOT_SPEC,
    FIXED_BID_TUNED_V1_BOT_SPEC,
    AGGRESSIVE_HEURISTIC_V2_BOT_SPEC,
    FIXED_BID_DIVERSE_V1_BOT_SPEC,
    BALANCED_HEURISTIC_V2_BOT_SPEC,
    FIXED_BID_BOT_SPEC,
    VECTOR_PPO_LARGE_V1_G350K_BOT_SPEC,
    PASSIVE_HEURISTIC_V2_BOT_SPEC,
    PASSIVE_HEURISTIC_V1_BOT_SPEC,
    AGGRESSIVE_HEURISTIC_V3_BOT_SPEC,
    BALANCED_HEURISTIC_V3_BOT_SPEC,
    PASSIVE_HEURISTIC_V3_BOT_SPEC,
)


def _index_specs(specs: tuple[BotSpec, ...]) -> Mapping[str, BotSpec]:
    names = tuple(spec.name for spec in specs)
    bot_ids = tuple(spec.bot_id for spec in specs)
    if len(set(names)) != len(names):
        raise ValueError("registered bot names must be unique")
    if len(set(bot_ids)) != len(bot_ids):
        raise ValueError("registered bot IDs must be unique")
    return MappingProxyType({spec.name: spec for spec in specs})


BOT_SPECS_BY_NAME = _index_specs(BOT_SPECS)


def registered_bot_specs() -> tuple[BotSpec, ...]:
    return BOT_SPECS
